### ISSUE TITLE
No Pre-training dataset and Steps to replicate

### ISSUE THREAD

**Issue by Anurag-Swarnim-Yadav** [antonio-mastropaolo/dl-training-vuln-patching#1]
@antonio-mastropaolo @training-vuln  Hey Antonia. I can't find your pre-training VRepair dataset, steps to pre-train on the VRepair dataset, and later Finetune on the VulRepair dataset.

**Comment by antonio-mastropaolo** [comment]
HI,

The dataset by Chen et al. is publicly available at: https://github.com/ASSERT-KTH/VRepair/tree/main

**Comment by Anurag-Swarnim-Yadav** [comment]
Hi @antonio-mastropaolo. Great Thank you. What about the pre-training step? I don't see a model load in your code. Please let me know. Thanks

**Comment by antonio-mastropaolo** [comment]
Hi @Anurag-Swarnim-Yadav 

Apologies for my late reply. I have been quite busy the past weeks. 
As far as the pre-training is concerned, I assume you are talking about the self-supervised pre-training. In that case, the model was further pre-trained for 10 epochs.
